### ISSUE TITLE
Ability to directly build vessels from the KCT menu

### ISSUE THREAD

**Issue by ghost** [linuxgurugamer/KCT#1]
Adding the idea from the forum thread. Being able to directly add vessels to the build menu would feel a lot sleeker overall instead of having to open VAB/SPH each time, loading the vessel you want, hitting Launch and then backing out again. A simple button to open a list of all saved craft to directly add them to the build queue would save a lot of trouble.

**Comment by linuxgurugamer** [comment]
New functionality in upcoming release
