### ISSUE TITLE
In part edit mode there is no way to overwrite existing build plan

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/KCT#15]
That means the vessel has to be loaded into VAB as usual the next time and then the build plan entry can be overwritten with the updated vessel.

**Comment by linuxgurugamer** [comment]
Im not sure I want it to be updatable.  Deletable, yes, and if it doesnt have that ill look into adding a deete button

**Comment by DocRockwell** [comment]
You can press alt+f12, disable input locks, then save or load.
