### ISSUE TITLE
After part edit the value hdId in MODULE HardDrive is changed to a random number

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/KCT#16]
... which renders the part useless.

Loading the craft, editing and saving it does not help, the changed value persists.

The ModuleCommand (or any other module which is used for experiments and storing the results) has to be replaced in VAB or the value has to be changed with a text editor inside the craft file.

Example:

After saving the craft file initially (or normalliy editing in VAB and overwriting it) the part which is ModuleCommand contains:
```	MODULE
	{
		name = HardDrive
		isEnabled = True
		hdId = 0
		stagingEnabled = True
		EVENTS
		{
		}
		ACTIONS
		{
		}
		UPGRADESAPPLIED
		{
		}
	}
```
and after editing it with KCT it's
```	MODULE
	{
		name = HardDrive
		isEnabled = True
		hdId = 2716355813
		stagingEnabled = True
		EVENTS
		{
		}
		ACTIONS
		{
		}
		UPGRADESAPPLIED
		{
		}
	}
```

**Comment by Gordon-Dry** [comment]
Cross reference:
https://github.com/Kerbalism/Kerbalism/issues/397

**Comment by SirMortimer** [comment]
that issue has no place on this project, it's purely kerbalism. please close this.

**Comment by Gordon-Dry** [comment]
Okay.
