### ISSUE TITLE
Reward VAB/SPH/R&D upgrade points via Contract Configurator?

### ISSUE THREAD

**Issue by nepphhh** [linuxgurugamer/KCT#20]
I'm hoping to write a patch for Contract Configurator that would allow me to directly modify the number of upgrade points invested in a building. What do I need to call to do this nicely through KCT rather than editing the savegame directly or something awful?

**Comment by linuxgurugamer** [comment]
Can you be a bit more specific as to what you re tryng to do?

**Comment by nepphhh** [comment]
Thanks! I think I've got enough tools up my sleeve to figure this one out now.
