### ISSUE TITLE
[feature request] - ability to trigger KCT recovery from stock game's "recover" button.

### ISSUE THREAD

**Issue by Dunbaratu** [linuxgurugamer/KCT#21]
One quality of life change that would have been useful when I first started using KCT as part of RP-1 would be if KCT's recover-into-storage option was somehow reachable from the stock green "recover" button, rather than only having access to it by opening KCT's window and finding the button there.

(It seems there is a game hook you can register to be notified of this event:
GameEvents.OnVesselRecoveryRequested.  It may be possible to work with that.)

Why?

1 - Because I had no idea this was even an option.  The button does not appear in the KCT window unless you are landed in the right spot (so if you don't think to open the KCT window for some reason just after landing an airplane, you never see the button the rest of the time.  And even then you won't see it unless you happen to open the SPH *part* of KCT while landed there.)  This makes it the sort of feature the user won't learn by just playing the game.  It's only something you find out about if you read the documentation page and find it there (remember that RP-1 is like 80 mods or so, so it isn't practical to do this for all of them).

2- Even after learning it this exists (from other RP-1 players) and is what I usually want to do (store an airplane for future contracts so I don't have to wait the build time for another), I still find myself constantly hitting that big green "recover" button, and not stopping myself until I've arleady clicked it.  It's such an ingrained habit for any KSP player that it's hard to break it.  And once you click it, there's no turning back.  You already prevented that plane from ever being re-used.

(Please note that this issue is here mostly as a discussion before I plan to actually look at the code and see if I can do this myself in a PR.  I was thinking of researching how to do this and submitting a PR, but I always like PR's to be attached to issues so I make the issue first, then address the issue in a PR later.)

**Comment by Dunbaratu** [comment]
What may make this hard to implement is that in a hook like ``GameEvents.OnVesselRecoveryRequested.Add(MyHook(Vessel))``, I don't think KSP provides any mechanism for ``MyHook()`` to "take" the event and tell KSP to abort doing what it would normally do.  (What is desired here is to give the player an option to do KCT's recovery *instead of * stock's recovery, but if the hook has no way to stop stock from continuing recovery after the hook is over, then you end up with KCT recovery *in addition to* stock's recovery, meaning you both get the airplane into KCT storage *and* stock will give you all the money back for it, which would be quite a cheat.)

**Comment by linuxgurugamer** [comment]
Added
