### ISSUE TITLE
LoadTree() doesn't check that fileNode is non-null

### ISSUE THREAD

**Issue by henrybauer** [linuxgurugamer/KCT#23]
KCT fails if there's no ModuleManager.TechTree:

![image](https://user-images.githubusercontent.com/5103358/63216092-c23fea80-c0f5-11e9-9874-50e5c617a1d6.png)

```
[LOG 11:54:27.463] [KCT] Loading tech tree from /Users/hunter2/KSP173/KSP.app/Contents/../../GameData\ModuleManager.TechTree
[WRN 11:54:27.463] File '/Users/hunter2/KSP173/KSP.app/Contents/../../GameData\ModuleManager.TechTree' does not exist
[ERR 11:54:27.463] Exception loading ScenarioModule KerbalConstructionTimeData: System.NullReferenceException: Object reference not set to an instance of an object
  at KerbalConstructionTime.KerbalConstructionTimeData.LoadTree () [0x00000] in <filename unknown>:0
  at KerbalConstructionTime.KerbalConstructionTimeData.OnLoad (.ConfigNode node) [0x00000] in <filename unknown>:0
  at ScenarioModule.Load (.ConfigNode node) [0x00000] in <filename unknown>:0
  at ScenarioRunner.AddModule (.ConfigNode node) [0x00000] in <filename unknown>:0
```

I disabled KCT, loaded the game, loaded a vessel, then exited the game so that it would create that file.  Then re-enabled KCT and went back in, and it worked.

The only way you'd get into this situation is by taking a fresh copy of KSP, installing mods (including KCT) and then copying over a saved game from another copy of KSP.  Which is exactly what I did.

https://github.com/linuxgurugamer/KCT/blob/master/Kerbal_Construction_Time/KerbalConstructionTime.cs#L44-L63

Looks like LoadTree() doesn't check that fileNode is non-null.

possible fix is change:
`if (fileNode.HasNode("TechTree"))`
to
`if (fileNode != null && fileNode.HasNode("TechTree"))`

**Comment by linuxgurugamer** [comment]
Thanks, will be in next release soon
