### ISSUE TITLE
Aircraft recovered to SPH rotated facing up

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/KCT#3]
After I recovered one of my aircraft and relaunched it, it was placed nose pointing straight up on the runway. Revert to SPH shows it like this:

![image](https://user-images.githubusercontent.com/717574/54878040-e806e300-4e26-11e9-9a3e-bb072eb2b5a8.png)

I believe this *may* have been a bug in a previous version of KCT, I remember seeing it happen before. 

I tried to edit it, rotate it correctly, and then save it, but that put me at a build time of 1 day.

**Comment by linuxgurugamer** [comment]
This is an old bug, I think it also manifests itself when launching a recovered plane

**Comment by linuxgurugamer** [comment]
Fixed in release 1.4.6

**Comment by tivec** [comment]
Amazing! Thank you very much for this, I'll give it a try as soon as I get a chance.
