### ISSUE TITLE
locked parts check

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/KCT#32]
[Persistent.zip](https://github.com/linuxgurugamer/KCT/files/3775992/Persistent.zip)
KCT 1.4.6.12 for KSP 1.7.3 seems to have a bug related to locked parts check. If I have a contract to test an undiscovered part, KCT doesn't let me launch this craft because the vessel allegedly contains unavailable parts.

**Comment by siimav** [comment]
#33 should fix it. Needs someone to validate the fix though.
