### ISSUE TITLE
Stutters in VAB at regular intervals

### ISSUE THREAD

**Issue by guitarheel** [linuxgurugamer/KCT#35]
I have stutters in the VAB and SPH occuring at regular intervals.  

This is a modded install over KSP 1.6.1.

[RELATED POST IN KSP FORUMS](https://forum.kerbalspaceprogram.com/index.php?/topic/189706-kct-causing-vab-stutters-at-regular-intervals/)
[MOD LIST](https://pastebin.com/MY5LSp3T)

**Comment by linuxgurugamer** [comment]
What sort of regular intervals?
You have a lot of mods installed.
It would help to post your messages in the correct forum where other interested and knowledgable people could see it, instead of a brand new post.  I've pinged the person who can help you, but it's not helpful.

**Comment by guitarheel** [comment]
Siimav referred me to you on the discord.  What forum should I post in? 

The intervals are about 500ms.  I can record a video from the VAB demonstrating this if necessary.

**Comment by linuxgurugamer** [comment]
Please reply as to whether this is happening with the latest version

**Comment by guitarheel** [comment]
Appears to be fixed!

**Comment by linuxgurugamer** [comment]
Thank you
