### ISSUE TITLE
Make P -> p

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/KCT#37]
https://github.com/linuxgurugamer/KCT/blob/3c568cb69f1ccb41edfd5f48bae34d4468f7bad9/Kerbal_Construction_Time/InstallChecker.cs#L45

If this is case sensitive then this is the culprit.

Plugins -> plugins

**Comment by Gordon-Dry** [comment]
Or fix the installchecker and make it allow uppercase and lowercase first letter in subfolder name.

**Comment by linuxgurugamer** [comment]
Please elaborate.  Plugins is supposed to be capitalized.  And I haven't seen an error like that for a while.
