### ISSUE TITLE
UI behaviour lost convenience (especially the Upgrades UI)

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/KCT#39]
The behaviour of the KCT UI was better before.

After opening the main UI with a click on the button in the stock button bar, I click on the "Upgrades" button.

I was used to that

- either the main UI stays open and the Upgrades UI opens besides of it (like with the Plans UI)
- or the main UI closes temporarily  and the Upgrades UI opens instead (and after closing the Upgrades UI the main UI restores as it was)

Now the main UI closes when the Upgrades UI opens.
After closing the Upgrades UI I have to click the button in the stock button bar twice to reopen the main UI.

**Comment by linuxgurugamer** [comment]
Fixed in upcoming release, thanks for the report
