### ISSUE TITLE
KCT Edit Stored Vessel blocking action group editor

### ISSUE THREAD

**Issue by KSpaceAcademy** [linuxgurugamer/KCT#46]
When using the "edit" functionality on a craft that exists in the KCT craft storage list, the action group editor window is "blocked" or frozen in the VAB/SPH. Going to Action group edit mode and then click a part on a craft make options blink and immediately disappear in the action group editor. Clearing input locks has no effect on behavior.

Confirmed with a totally fresh install of KSP from Steam (1.8.1.2694) and ONLY the KCT Mod plus its listed dependencies in the below image:

![image](https://user-images.githubusercontent.com/58754714/70581233-863d0380-1b84-11ea-9cde-1784bacf5504.png)

Steps to reproduce:

1. Have a KSP install with KCT, with a save that has a craft which has been recovered to KCT craft inventory
2. On KSC Scene, Click the * next to a stored craft, and click edit
3. Click "Cancel Edits" in KCT.
4. On KSC Scene, Click the * next to a stored craft, and click edit (again)
5. In the SPH/VAB, switch to action group editor mode. 
6. Click a part on the craft. Action group editor flickers briefly but does not show any options
6a. Also, you cannot click any action groups in the action group editor to see existing part actions
7. Even if you go back to KSC Scene, reenter VAB/SPH, and create new vessel, Action Group editor is still broken
8. Even if you completely reload the game save (not restart KSP) Action group editor is still broken
9. To resolve, completely restart KSP

For a full video showing steps to reproduce be sure to check out the timestamp at:
 https://www.twitch.tv/videos/519772678?t=03h00m01s

Heh

**Comment by DefiantZombie** [comment]
Can confirm the repro steps

KSP 1.8.1
ClickThroughBlocker 0.1.9.4
KerbalConstructionTime 1.4.7.6-180
MagiCore 1.3.2.3
ToolbarControl 0.1.9.4

I noticed CTB spamming NRE as soon as the scene switches to the editor after choosing Edit the 2nd time. Attached a clean log.

[KSP.log](https://github.com/linuxgurugamer/KCT/files/3947844/KSP.log)

**Comment by linuxgurugamer** [comment]
What about using 1.4.7.5?

**Comment by DefiantZombie** [comment]
Same issue in 1.4.7.5

Also verified a case we hadn't checked. The bug is triggered when edits are saved as well.

**Comment by linuxgurugamer** [comment]
The problem is specific to the 1.8.1 version, and is related to the Unity upgrade.  I've been able to isolate it to some extent, will let you all know when it's fixed

**Comment by linuxgurugamer** [comment]
I found and fixed the bug.  It was NOT in KCT, but was in the ClickThroughBlocker.
Please update to ClickThroughBlocker v0.1.9.5 to fix:
https://github.com/linuxgurugamer/ClickThroughBlocker/releases/tag/0.1.9.5
