### ISSUE TITLE
Reorientation of VAB craft on launch since 1.4.6

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/KCT#5]
Since 1.4.6, it seems that the second I press stage on a vessel created from the VAB, it immediately switches to 90 degrees off and goes boom. Video below:

http://i.tivec.org/2019-03-27_19-41-35.mp4

This seems to happen to new vessels built in the VAB as well as vessels in the build queue. Pretty explosions though! :D

 Should also be noted I'm using the mod VABReorienter by Snark so the angle it goes off might not be what's expected. Nonetheless, it shouldn't tilt by 90 when launching. I have not yet had a chance to test without VABReorienter, but all that one does is rotate the craft to face the proper direction in the VAB, much like you do if you rotate it around the up axis yourself in the editor.

I'll run a test on this tomorrow.

**Comment by GarwelGarwel** [comment]
I confirm this issue. I had it without VABReorienter.

**Comment by linuxgurugamer** [comment]
This was fixed in 1.4.6.1
