### ISSUE TITLE
Airlaunch for Stock

### ISSUE THREAD

**Issue by siimav** [linuxgurugamer/KCT#50]
Continuation of #48.
To make this feature available for stock players, some configs would need to be defined in \GameData\KerbalConstructionTime\AirlaunchLevels.cfg file. [Here are the realistic configs](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/CustomBarnKit.cfg#L141-L197) I created for RP-1. 
Ideally some dummy PartUpgrade nodes would also be added to the tech tree to notify the player about what upgrades are available and what effect they have. Config for RP-1 can be seen [here.](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Tree/AirlaunchTechlevels.cfg)
There's also cost and time associated with airlaunch similar to how the rollout works. For this there are 2 new formulas [here](https://github.com/KSP-RO/KCT/blob/4788b5bf532f2389e9ae4907b6247e4b96a62c7b/Kerbal_Construction_Time/KCT_PresetManager.cs#L355-L356). At this point I set the default values to 25% of BP and 25% of vessel's Effective cost but didn't make the formulas editable through the settings UI. For RP-1 these values will be configured through the custom preset file anyway but stock might actually need those to be editable.

As for what actual values to use for stock - I personally have no idea. It's been too long since I played a stock career so I don't have the slightest hint of what parameters would fit some average stock vessel.

**Comment by linuxgurugamer** [comment]
Just looked at your configs, they actually look reasonable.
I'll add them and try them out.  I'll put a NEEDS[!RP-0] into them so that any changes made will not be active in RP0

**Comment by linuxgurugamer** [comment]
Oh, regarding the edits, for now I don't think I'll put that in, will depend on how much work is involved.

**Comment by siimav** [comment]
> NEEDS[!RP-0]

No, don't put that there. The RP-1 MM patch removes all configs that might already exist.

**Comment by linuxgurugamer** [comment]
Ok.  What I'll do then is to get it set up and push to github, but not release until you've had a chance to test and make sure it's not causing any problem

**Comment by siimav** [comment]
Sounds good to me

**Comment by linuxgurugamer** [comment]
What does:

// All sizes have additional 3, 2, 1 m added on top of the desired value to mitigate B9 reporting bigger sizes than actual

mean?  Which value, etc?

**Comment by linuxgurugamer** [comment]
I've pushed the new configs to Github, but haven't released them to anybody yet.  From the little testing I did, seems to work nicely

**Comment by siimav** [comment]
The issue is with B9 Procedural wings that can make the reported dimensions of the vessel bigger than it actually is. I think only swept wings somehow cause this issue. RO/RP-1 players use **only** B9 wings for designing aerodynamic surfaces so I added a rough workaround to the bug. The added values are 3m to width; 2m to height; 1m to length.

**Comment by siimav** [comment]
https://github.com/linuxgurugamer/KCT/commit/a92e6f901921a4263d3293806ff99feb10544914#diff-17bb201fe04466543ab4fe07f3eec96fR6
Btw, those tech names are specific to RP-1 and you would need to find some tech nodes from the stock tree to replace with.

**Comment by linuxgurugamer** [comment]
Oh, ok.  Thanks for reviewing, I'll get that udated this evening

**Comment by linuxgurugamer** [comment]
Completed in version 1.4.7.11
