### ISSUE TITLE
toolbar icon issue

### ISSUE THREAD

**Issue by eberkain** [linuxgurugamer/KCT#54]
If you  use toolbar controller to move the KCT icon to blizzys toolbar and then go to the space center view you get constant log spam with.  

> [ERR 20:17:45.554] [Toolbar] [ERROR] button texture not found: KerbalConstructionTime/PluginData/Icons/KCT_on-24

I confirmed the icon is at that location and nothing appears misspelled.

**Comment by linuxgurugamer** [comment]
Complete log please, there may be something earlier

**Comment by linuxgurugamer** [comment]
Also, what if you are in the space center and change the icon?

**Comment by linuxgurugamer** [comment]
Just so you know, I started KSP, went to the flight scene, changed the location of KCT from stock to Blizzy, and then went to the space center.  No errors

**Comment by eberkain** [comment]
I will investigate when I get home, I could have swore I tested that with just a minimal KCT install before reporting it.

**Comment by eberkain** [comment]
I copied my game folder to a new loc and deleted everything in the gamedata folder but Squad and SquadExpansion, then used CKAN to install Toolbar and KCT, which included its dependencies and recommendations (sans ScrapIt! since I play Kerbalism generally). 

I started a new game in sandbox. Used toolbar control to switch the KCT icon over to the toolbar.  Used the toolbar control to make the button visible.  Then went to the tracking center and back to the space center view and I see error spam using the in-game console, about 10/sec or so.  

Here is log file.  
https://drive.google.com/open?id=19D_2L2_8jj56j5u0dxFcpUMO_XDIyhmN

**Comment by linuxgurugamer** [comment]
I wonder if this is related to #36

**Comment by linuxgurugamer** [comment]
What scene were you in when you switched the KCT icon over to the toolbar?

**Comment by linuxgurugamer** [comment]
I have done exactly the same thing:
Made new install
Set it up with CKAN
Installed KCT & Toolbar, along with dependencies.  Also added ZeroMiniAVC.

All mods installed are:
ClickThrough Blocker (ClickThroughBlocker 0.1.9.5)
Crew R&R (CrewQueueTwo 1.1.10.4)
Kerbal Alarm Clock (KerbalAlarmClock v3.12.0.0)
Kerbal Construction Time (KerbalConstructionTime 1:1.4.7.7)
KRASH - Kerbal Ramification Artifical Simulation Hub (simulation mod for KSP) (KRASH 0.5.31.4)
MagiCore (MagiCore 1.3.2.3)
Module Manager (ModuleManager 4.1.3)
StageRecovery (StageRecovery 1.9.2.1)
Toolbar (Toolbar 1:1.8.0.5)
Toolbar Controller (ToolbarController 1:0.1.9.4)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)


Started new save in sandbox mod
Got to SpaceCenter
Opened the yellow wrench.
Changed KCT to be toolbar
Closed window
Opened Toolbar & madke KCT visible.
Went into tracking station
Went back to SpaceCenter

No errors

**Comment by linuxgurugamer** [comment]
So install MiniAVC and see if it happens again.  The MiniAVC is seriously broken in 1.8, I'm working on it

**Comment by linuxgurugamer** [comment]
I just realized you gave me the KSP.log.  I need the Player.log, it has more info

**Comment by eberkain** [comment]
I tried again with the same mods and Zero MiniAVC installed and still get the same error.  

here are both logs from this time
https://drive.google.com/drive/folders/12DEmICY-RniTGTB1Wev8g0Q74LAUpie8?usp=sharing

**Comment by linuxgurugamer** [comment]
I see two differences,neither of which makes sense, but might as well check it out:

1.  You are running it from your desktop
2.  You have spaces in the path.

To eliminate this, could you move the entire "Kerbal Space Program" to "c:ksp" and test again. 

In the meantime, I'm trying to add some extra debugging statements to a custom build of the Toolbarcontroller, I'll post a message with a link when I have it ready

**Comment by linuxgurugamer** [comment]
Have you resized any part of the UI?

**Comment by linuxgurugamer** [comment]
Ok.  Here is a special build of the toolbar, please unzip it into: 000_Toolbar\Plugins

https://www.dropbox.com/s/k3rp42ab8shrmrv/aaa_Toolbar.zip?dl=1

I did make one change, which _might_ fix it (I doubt it but it needed to be changed)

Let me know how it goes.  It IS going to be spamming the log file, so be patient with it.
Thanks

**Comment by eberkain** [comment]
> Have you resized any part of the UI?
yes, I have bad eyesight so I use the games built-in UI scaling set to 120%

I moved the ksp folder to root and swapped the .dll but sadly I still get the error.  
https://drive.google.com/open?id=1TNZoB3JNuiWijJCCsuiuhb35vygBkApo

I tried resetting all the game options back to default using the in-game function and the error no longer occurs so I think it may indeed have something to do with UI scaling.

**Comment by linuxgurugamer** [comment]
There are two scales for the UI, which one did you change?
One is labeled as UI Scale, the other is Apps Scale

**Comment by linuxgurugamer** [comment]
I was _just now_ able to replicate the problem!!!!

**Comment by linuxgurugamer** [comment]
Ok, I found the problem.  It was in KCT, but was an odd interaction with the Blizzy toolbar code when a non-100% size was used
I'll be getting an update out either this evening or tomorrow.

Thank you for your patience.

**Comment by eberkain** [comment]
Thank you for all your hard work on all the mods.

**Comment by linuxgurugamer** [comment]
Just released a new beta which fixes this and other problems:

https://github.com/linuxgurugamer/KCT/releases/tag/1.4.7.10
