### ISSUE TITLE
Deleting 1st launchpad while new launchpad is building causes multiple bugs

### ISSUE THREAD

**Issue by Teykn** [linuxgurugamer/KCT#59]
While building a new launchpad, deleting a launchpad causes KCT to break entirely. These are the bugs that are caused through this issue:

1. Build rates, at 1x time warp, speed up to rates equivalent to 100-1000x  time warp
2. All r&d research is halted
3. Launchpad isn't built, stuck at "00:00:00:00"

**Comment by siimav** [comment]
I'm unable to replicate this issue

**Comment by siimav** [comment]
Actually never mind, I think I got it...
