### ISSUE TITLE
Merging built vessels

### ISSUE THREAD

**Issue by DarthPointer** [linuxgurugamer/KCT#65]
Imagine me having a reusable rocket. As it is built with the first payload, I launch it, return and wish to place the next payload on it. Having multiple pipelines makes it easier: I can start producing them at the same time, having them ready faster than if I had only one pipeline.

But at this moment, KCT provides no functionallity to merge separatelly built crafts into one. I don't know, if it is an easy feature to be added, but give it a try, please!

**Comment by linuxgurugamer** [comment]
Not going to happen, sorry.  Best you can do is to recover them for money.  You can try to recover to the VAB, and when it's recovered, you can edit it and relaunch, but that's about as far as it can go

**Comment by DarthPointer** [comment]
Can we get able to open saved crafts folder when editing a built vessel? I mean that yellow button in the top of the editor.

Example: I need 3 commsats in orbit. I launch the first, recover LV and add it a new copy of satellite using merge button in "open craft" menu, not building it manually from scratch.

**Comment by linuxgurugamer** [comment]
You should be able to do so.  Or, save the commsat as an assembly, then merge the assembly

**Comment by DarthPointer** [comment]
Thats weird, as I remember, that yellow button is inactive when I edit an existing craft. Need to check it.

**Comment by DarthPointer** [comment]
It is inactive when I edit a being built vessel.
