### ISSUE TITLE
infinite time of rolling out

### ISSUE THREAD

**Issue by hsp70** [linuxgurugamer/KCT#68]
it happened 2 times when I am playing rp0.  I only can abort the launchpad and create a new one.
![image](https://user-images.githubusercontent.com/39071523/79857060-cbf5bc80-83ff-11ea-825a-cdb8730f58a4.png)
the version is:
![image](https://user-images.githubusercontent.com/39071523/79857226-0b240d80-8400-11ea-84f0-e3730d123ad8.png)

**Comment by linuxgurugamer** [comment]
First, I don't support RO, you need to post in the RO
Second, please don't post support questions here, post in the forum.
Third, you are running KSP 1.3.1, which is rather old (based on the bottom line)
and finally,  1.4.7.13 is not valid for that version of KSP

Forgot to mention, you should ALWAYS provide a log file (link to it)

Closing this, please repost in the proper forum, thank you
