### ISSUE TITLE
KCT trying to load crewmembers to non-crewable parts

### ISSUE THREAD

**Issue by austinjames314** [linuxgurugamer/KCT#7]
Raised from the KSP forums. Multiple reports of vessels loading without any crew on board, despite the designations set in the KCT launch screen.

https://forum.kerbalspaceprogram.com/index.php?/topic/182877-151-161-kerbal-construction-time-unrapid-planned-assembly/&do=findComment&comment=3582921

At least two log files from different users show KCT attempting load the crew into random parts, instead of the designated parts. e.g:

`[WRN 16:19:33.282] Cannot add crewmember Janvis Kerman to smallCtrlSrf. Part Crew Capacity Exceeded.`
`[ERR 16:19:33.282] Error when assigning Janvis Kerman to smallCtrlSrf`

and

`[WRN 19:52:58.385] Cannot add crewmember Valentina Kerman to solidBooster.sm.v2. Part Crew Capacity Exceeded.`
`[ERR 19:52:58.385] Error when assigning Valentina Kerman to solidBooster.sm.v2`

**Comment by austinjames314** [comment]
This was on KSP 1.6.1, and KCT 1.4.6.2-Beta-3.

Rolling back to KCT 1.4.6 resolved the problem for now.

Edit: Oh god the stuttering! I forgot how bad it was!

**Comment by linuxgurugamer** [comment]
Fixed in the latest release
