### ISSUE TITLE
Crash at lastest step (loading extension)

### ISSUE THREAD

**Issue by Jorropo** [linuxgurugamer/KCT#78]
KSP softlocks (or inifinite loading if you want):
```
[LOG 21:00:52.396] No Expansions detected
[EXC 21:00:52.419] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
	System.Reflection.Assembly.GetTypes () (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	AssemblyLoader.GetTypesOfClassesImplementingInterface[T] () (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	Expansions.Missions.MissionsUtils.InitialiseAdjusterTypes () (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	Expansions.ExpansionsLoader+<LoadExpansions>d__21.MoveNext () (at <c1858a3f77504bd1aaa946fdccf84670>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	Expansions.ExpansionsLoader:StartLoad()
	<LoadSystems>d__11:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[LOG 21:00:52.420] [ModuleManager] Intercepted a ReflectionTypeLoadException. List of broken DLLs:
KerbalConstructionTime 1.4.8.0 GameData\KerbalConstructionTime\Plugins\KerbalConstructionTime.dll
```
I have attached the full log file:
[KSP.log](https://github.com/linuxgurugamer/KCT/files/5288909/KSP.log)

**Comment by Jorropo** [comment]
Edit, I've forgot to add magicore, still doesn't work without, newer log :
[KSP.log](https://github.com/linuxgurugamer/KCT/files/5288945/KSP.log)

**Comment by linuxgurugamer** [comment]
Two things:

1.  For support, please post on the forum, where other people can see and help.  I haven't looked at the log for the following reason:
2.  I need the Player.log, not the KSP.log. It's failing on loading a part, not KSP.

I'm going to close this, please post a Player.log in the KCP forum:
https://forum.kerbalspaceprogram.com/index.php?/topic/182877-173-18x-19x-kerbal-construction-time-unrapid-planned-assembly/

Please ping me as I'm going to be offline for the next day or so, that way I'll have a better chance of seeing it (ping mean putting @linuxgurugamer  in the post)

**Comment by Jorropo** [comment]
Quick followup in case someone find this somehow through google search.
I just fogot to install other deps, MagiCore is not the only dep (you can find them a bit bellow in the forum thread :) )
