### ISSUE TITLE
Error in Loading KCT Data (with RP-1)

### ISSUE THREAD

**Issue by Peter-JY** [linuxgurugamer/KCT#81]
KCT reported a error and need I to send "KSP.log" to here. It said that this bug will make things "seriously broken".

In Start Menu:
“Incorrect Kerbal Construction Time Installation
Kerbal Construction Time has been installed incorrectly and will not function properly. KCT is now integrated into RP-1 which means that installing it as a separate mod is no longer allowed.
Incorrect path(s):
GameData\KerbalConstructionTime\Plugins\KerbalConstruction.dll”

In Game:
"Error Loading KCT Data
ERROR! An error occurred while loading KCT data. Things will be seriously broken! Please report this error to RP-1 Github and attach the log file. The game will be UNPLAYBALE in this state."

[issues in RP-1 Github page](https://github.com/KSP-RO/RP-0/issues/1421)
[KSP.log](https://drive.google.com/drive/folders/1CRF7Vnx7mS00I4GunpDQaU9r-GyBDbTp?usp=sharing)

Game Version: 1.8.1 (build id 02694) with all DLCs

**Comment by siimav** [comment]
This isn't the RP-1 GitHub
