### ISSUE TITLE
KerbalEVA part bug

### ISSUE THREAD

**Issue by Lucaspec72** [linuxgurugamer/KCT#82]
command pods that have the kerbals physically there (example the biplane cockpit from firespitter) get bugged if kerbals are in those commands pods when it gets recovered, as kerbals are considered a part of the ship when in this state, so it adds the KerbalEVA part, that floods the console with errors, make the user unable to edit the ship because of said error messages, adding another part that doesn't actually exist and probably some other issues i'm forgetting. from what i've tested, making kerbals leave those kind of command pods before recovery avoids this problem, it doesn't fix it however. could this be  fixed ?

**Comment by linuxgurugamer** [comment]
I'll look into it, not sure what's involved.  But you gave me a good description of the problem, I'll be able to replicate it

**Comment by linuxgurugamer** [comment]
Fixed in latest release

**Comment by Lucaspec72** [comment]
nice
