### ISSUE TITLE
VAB building Plans "spawning" in VAB

### ISSUE THREAD

**Issue by NightShift10125** [linuxgurugamer/KCT#88]
I found a bug where ships put in the building plans spawn in the VAB.
In the image I just booted up the editor in the VAB with what was suppose to be a cleaned space but my "Super Mun 3" and a craft I removed previously from building plans spawn.
I have found that reloading the game fixes the bug and I believe the bug is caused after reloading the game with something in the building plans.
![image_2021-07-12_073347](https://user-images.githubusercontent.com/42304378/125296401-7dbe2900-e2e3-11eb-8b64-5023d4833855.png)

**Comment by NightShift10125** [comment]
News update, it happens in the SPH too... 
![image_2021-07-12_073800](https://user-images.githubusercontent.com/42304378/125297004-148ae580-e2e4-11eb-98d2-1a44fe4c5d9e.png)

**Comment by NightShift10125** [comment]
I do believe this is part of the same bug?
![image_2021-07-12_080423](https://user-images.githubusercontent.com/42304378/125300977-c4ae1d80-e2e7-11eb-93b3-6755f1d5f06c.png)

**Comment by DarthPointer** [comment]
@NightShift10125 I have seen this bug to occur in flight scene, try updating scatterer.
