### ISSUE TITLE
Recovered crafts in the editor don't reset

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/KCT#9]
Things like science experiments, SRBs, etc should be reset at some point

**Comment by pietralbi** [comment]
Notice that it is likely a regression introduced in the recent commits: I clearly remember using 1.4.6 on KSP 1.6.1 and recovered crafts were reset correctly

**Comment by Snucker** [comment]
not sure if this is the cause of the bug but KCT_BuildListVessel.cs line 329:
for (int i1 = node.values.Count - 1; i >= 0; i--)
should be
for (int i1 = node.values.Count - 1; i1 >= 0; i1--)

**Comment by linuxgurugamer** [comment]
Nice catch, thanks
