### ISSUE TITLE
Remove `new GUIStyle()` calls from UI updates

### ISSUE THREAD

**Issue by siimav** [linuxgurugamer/KCT#92]
The Principia developers [found out](https://github.com/mockingbirdnest/Principia/issues/3064#issuecomment-968072299) that `GUIStyle` instances are not GC'ed correctly and thus will cause serious memory leaks when continously allocated from the Update cycle. I found a couple of instances of this happening in the RP-1 fork so I believe that yours is affected as well.

**Comment by linuxgurugamer** [comment]
That's an old issue on many mods.  If someone isn't careful, that happens a lot. 
Thanks for the update, I'll take a look, but if you could let me know where you found it, might save me some time

**Comment by siimav** [comment]
I haven't looked through the code on your fork but I believe that KCT_GUI_BuildList and KCT_GUI_Presets are affected.

**Comment by linuxgurugamer** [comment]
Just so  you know, I've just finished reviewing the code.  Looks like I had fixed this a while ago, but I did find one outlier which I fixed.
Thanks
