### ISSUE TITLE
Construction time is always shown as 0 minutes, and won't let me build

### ISSUE THREAD

**Issue by K9Advanteaux** [linuxgurugamer/KCT#95]
I build a rocket, but when I open the menu that shows how long it'll take to build it always shows as 0 minutes, 0 hours, 0 days, etc. Research works as intended, I tried that, and it shows the proper time and lets me warp to its completion.

Even with the 0 minutes, it won't let me build anything at all. I click the button and nothing happens. I don't get kicked out or crash or anything dramatic like that, just literally nothing happens.

I'm curious to know if I'm doing something wrong or if this is a common issue for people.

**Comment by linuxgurugamer** [comment]
Please post on the forums, this is not a support location.  that way other people can help.

When you do, post a link to an uploaded copy of the Player.log

[https://forum.kerbalspaceprogram.com/index.php?/topic/182877-151-161-kerbal-construction-time-unrapid-planned-assembly/](https://forum.kerbalspaceprogram.com/index.php?/topic/182877-151-161-kerbal-construction-time-unrapid-planned-assembly/)
